#platform :ios, ‘7.0’

target ‘xbed’ do
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'IQKeyboardManager'
    pod 'Mantle', '~> 2.0.6'
    pod 'Masonry'
    pod 'MJRefresh', '~> 3.0.8'
    pod 'STAlertView', '~> 1.0.0'
    pod 'Base64', '~> 1.1.2'
    pod 'GTMBase64', '~> 1.0.0'
    pod 'MD5Digest', '~> 1.1.0'
    pod 'UIView+FrameEx', '~> 0.0.1'
    pod 'UIColor+Hex', '~> 1.0.1'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'NJKWebViewProgress', '~> 0.2.3'
    pod 'SMPageControl', '~> 1.2'
    pod 'NSDate+Calendar', '~> 0.0.8'
    pod 'NSDate+Helper', '~> 1.0.4'
    pod 'AMapSearch'
    pod 'AMapLocation'
    pod 'AMapNavi'
    pod 'HTMLReader', '~> 0.9.6'
    pod 'BKPhotoBrowser'
    pod 'TZImagePickerController', '~> 1.4.4'
    pod 'Toast', '~> 3.0'
    pod 'Qiniu'
    pod 'UMengAnalytics-NO-IDFA'
    pod 'GetuiSDK-NoIDFA'
    pod 'JPFPSStatus', '~> 0.1'
    pod 'FSTextView'
    pod 'LeoTextField'
    pod 'LeoRadioButton'
    pod 'LeoPayManager'
end
